from langchain_openai  import AzureChatOpenAI
import os
from langchain import PromptTemplate, LLMChain

class Summarization:

    def summarize_timeline(self, text):
        """
        Takes a full transcript generated by extract_audio plugin and
        returns a summarized timeline
        :param text: full transcript generated by extract_audio plugin 
        :return: summarized timeline
        """

        llm = AzureChatOpenAI(
            temperature=0,
            openai_api_version="2023-09-01-preview",
            deployment_name="GPT-4o-mini", #Deployment name
            azure_endpoint=os.environ["OPENAI_API_BASE"],
            model_name="GPT-4o-mini"
        )
    

        summarize_template_string = """I will give you a transcript of a video. The transcript contains phrases prefixed by the timestamp where the phrase starts. I want you to identify between three and ten main sections of the video. For each section you will create a brief title prefixed with the start timestamp of the section, obtained by the first phrase of the section. 

EXAMPLE ANSWER
00:00 - Title 1
00:33 - Title 2
01:23 - Title 3

[DATA]
{text}
        """
        prompt = PromptTemplate(
            template=summarize_template_string, 
            input_variables=["text"])
        
        invocation = prompt | llm
        response = invocation.invoke({"text": text})
        return response.content